camera: hik
odom2camera:
  xyz: '"0.1 0.005 0.03"'
  # rpy: '"0.0 0.0 0.025"'
  # xyz: '"0.134554 0.000950 0.035122"'
  rpy: '"0.0 0.0 0.0066"'

detector_log_level: INFO
tracker_log_level: INFO
serial_log_level: INFO
simulator_log_level: INFO
