# /camera_node:
#   ros__parameters:
#     camera_info_url: package://rm_vision_bringup/config/camera_info.yaml
#     exposure_time: 500
#     gain: 16.0

/camera_node:
  ros__parameters:
    camera_info_url: package://rm_vision_bringup/config/camera_info.yaml
    # exposure_time: 10000.0
    exposure_time: 500.0
    gain: 16.0
    autocap: true
    frame_rate: 249.0
    frame_id: camera_optical_frame

# 串口节点
/serial_driver:
  ros__parameters:
    timestamp_offset: 0.0 #时间戳偏移量
    vid: "16d0"
    pid: "1492"

# 装甲板识别节点
/armor_detector:
  ros__parameters:
    debug: true

    detect_color: 0 # 0: red, 1: blue
    binary_thres: 85

    light.min_ratio: 0.1 # 灯条 (长/宽) 的比值 Detector::isLight 函数中判断是否为灯条
    armor.min_light_ratio: 0.8 # 装甲板 (长/宽) 的比值 Detector::isArmor 函数中判断是否为装甲板

    classifier_threshold: 0.6
    ignore_classes: ["negative"]

# 装甲板观测节点
/armor_tracker:
  ros__parameters:
    target_frame: gimbal_odom # 目标坐标系
    max_armor_distance: 13.0 # 极限最远可观测装甲板距离

    ekf:
      sigma2_q_xyz: 0.5 # 位置坐标过程噪声方差
      sigma2_q_yaw: 5.0 #偏航角过程噪声方差
      sigma2_q_r: 10.0 #位置坐标过程噪声方差

      r_xyz_factor: 0.15 #位置坐标观测噪声协方差系数
      r_yaw: 0.1 #偏航角观测噪声协方差

    tracker: #标记{tracker 参数}
      max_match_distance: 0.3
      max_match_yaw_diff: 1.0

      # 弹道解算
      k: 0.0
      bias_time: 10
      s_bias: 0.0
      z_bias: 0.0
      pitch_bias: 0.0
      calculate_mode: true

      tracking_thres: 5
      lost_time_thres: 1.0
      table:
        max_x: 13.0
        min_x: 0.0
        max_y: 2.0
        min_y: -1.0
        resolution: 0.01
        filename: "/home/bandiera/Desktop/AUTO-Aming-system/install/armor_tracker/share/armor_tracker/tools/hero_13_table.bin"

/hand_eye_calibrate_node:
  ros__parameters:
    image_topic: "/image_raw" # 图像话题名称
    camera_info_topic: "/camera_info" # 相机信息话题名称
    joint_states_topic: "/joint_states" # 关节状态话题名称
    yaw_joint_name: "yaw_joint" # Yaw 关节名称
    pitch_joint_name: "pitch_joint" # Pitch 关节名称

    publish_debug_image: true # 是否发布调试图像
    debug_image_topic: "/rm_hand_eye/debug_image" # 调试图像话题名称

    board_cols: 11 # 标定板列数
    board_rows: 8 # 标定板行数
    square_size: 0.02 # 方格尺寸（米）

    max_age_sec: 0.25 # 采样时用于过滤过旧检测结果的时间阈值（秒）
    handeye_method: "TSAI" # 手眼标定方法：TSAI, PARK, HORAUD, ANDREFF, DANIILIDIS
    invert_pitch_sign: false # 若云台 pitch 角正方向与预期相反，则置 true

